language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lxq1"
  - git config user.email "forwardlee@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${github}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:    
   - GH_REF: github.com/lxq1/lxq1.github.io.git